Add boundary-based influence scores, the LiSSA IHVP calculator and the Arnoldi algorithm
deel-ai/influenciae pull request #22
Opened 2023-02-10 17:38 UTC by Agustin-Picard

## Boundary-based methods

Instead of computing the influence of a point using influence functions, we propose to do so by measuring the distance of each data-point to the decision boundary. This can be done in two different ways: by using deep-fool to find the closest adversarial example, or by finding the minimum norm delta in the model's weights so the sample is classified differently.

Their performance is lesser than the other methods in the library, but we have found them to be more robust to hyperparameter changes.

## LiSSA

In [Understanding Black-box Predictions via Influence Functions](https://arxiv.org/abs/1703.04730), the authors propose to use an iterative procedure for computing IHVPs: LiSSA. We have added a TF-optimized version of this algorithm to our other two IHVP calculators, that can be used when they don't perform well enough.

## Arnoldi

We implemented the efficient approximation for influence scores proposed in [Scaling Up Influence Functions](https://arxiv.org/abs/2112.03052).

All these methods were also included in the benchmarking module for easy testing.

2023-02-20 08:37 UTC, lucashervier requested changes
Such a huge PR! Most of it is really neat. I spotted some minor errors: there are some commented code left, I believe some variable names are not really explicit and I am not convinced by some test where magic constants appear. In general, I believe we should work on a refactoring of the test as many lines are replica from other tests. In addition, in the future we should try to avoid so many if statements. However, congratulation for the implementation of the 3 totally new methods!

2023-02-20 08:37 UTC, lucashervier commented on benchmark_runner.py
> +        elif method_name == 'boundary_weights':
It is a lot of conditional statement, maybe we should consider refactor it at some point..

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/benchmark/influence_factory.py
> +              train_info: Any) -> WeightsBoundaryCalculator:
Since it will be set to None, why isn't it defaulting to None ?

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/benchmark/influence_factory.py
> +              train_info: Any) -> SampleBoundaryCalculator:
Idem

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/benchmark/influence_factory.py
> +            None, as no additional information is required in this case.
Idem

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/influence/arnoldi_influence_calculator.py
> +        # hessian = W^T * A * W
We should clear the commented code :)

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/influence/arnoldi_influence_calculator.py
> +class ArnoldiInfluenceCalculator(BaseInfluenceCalculator):
I am not very fond of the variables names but if it is mirroring the original implementation then I guess it is ok!

2023-02-20 08:37 UTC, lucashervier commented on deel/influenciae/influence/second_order_influence_calculator.py
> +        if isinstance(self.ihvp_calculator, ExactIHVP):
We should consider refactoring here instead of all those conditionals. I note it here so we do not forget it in future work

2023-02-20 08:37 UTC, lucashervier commented on tests/boundary_based/test_sample_boundary.py
> +def test_compute_influence_shape():
I think we should not have tests with constant values and without explaining how we get the `expected_results` from those constants. It makes the test really unclear on how it challenge the results

2023-02-20 08:37 UTC, lucashervier commented on tests/boundary_based/test_sample_boundary.py
> +def test_compute_influence_vector():
Idem

2023-02-20 08:37 UTC, lucashervier commented on tests/boundary_based/test_weights_boundary.py
> +    assert tf.reduce_all(tf.shape(influence_computed_score) == tf.convert_to_tensor([10, 1], dtype=tf.int32))
Magic constant

2023-02-20 08:37 UTC, lucashervier commented on tests/boundary_based/test_weights_boundary.py
> +    influence_computed_expected = tf.convert_to_tensor([[-np.sqrt(2.0) * 2.0]], dtype=tf.float32)
Magic constant also

2023-02-20 08:37 UTC, lucashervier commented on tests/common/test_ihvp_factory.py
> +    # case 1
What are the cases ?

2023-02-21 17:22 UTC, Agustin-Picard commented
I've adressed all the remarks except for the conditionals and the variable names in the `ArnoldiInfluenceCalculator` class (as it does follow the paper's notation). Thanks for the thorough review!

2023-02-22 09:02 UTC, lucashervier commented on tests/boundary_based/test_sample_boundary.py
> +def test_compute_influence_shape():
Hope we do not forget to change it in the next PR

2023-02-22 09:02 UTC, lucashervier commented on tests/boundary_based/test_weights_boundary.py
> +    influence_computed_expected = tf.convert_to_tensor([[-np.sqrt(2.0) * 2.0]], dtype=tf.float32)
idem...

2023-02-22 09:03 UTC, lucashervier reviewed
LGTM. However, we should think about the magic constant in the tests for the next PR.

2023-02-22 09:03 UTC, lucashervier approved these changes

2023-02-22 09:05 UTC, lucashervier requested changes
There is a missing bump2version commit I believe. I almost forget it!

2023-02-22 14:18 UTC, lucashervier approved these changes
Nice work @Agustin-Picard !

2023-02-22 14:56 UTC, merged